# Generated by Django 6.0.1 on 2026-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contando_amor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casal',
            name='data_de_inicio_relacionamento',
            field=models.DateField(),
        ),
    ]
