# Generated by Django 6.0.1 on 2026-01-22 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contando_amor', '0002_alter_casal_data_de_inicio_relacionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='casal',
            name='page_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
